import csv

words = [
    "banana", "tiger", "ocean", "mountain", "sun",
    "moon", "forest", "river", "guitar", "book",
    "piano", "flower", "butterfly", "rainbow", "star",
    "cloud", "bird", "elephant", "coffee", "cake",
    "computer", "phone", "chair", "table", "lamp",
    "window", "door", "car", "bicycle", "train",
    "plane", "boat", "fish", "dog", "cat",
    "horse", "snake", "lion", "zebra", "giraffe",
    "monkey", "turtle", "octopus", "whale", "dolphin",
    "shark", "crocodile", "dragon", "unicorn", "mermaid",
    "wizard", "witch", "vampire", "ghost", "zombie",
    "werewolf", "fairy", "elf", "dwarf", "goblin",
    "knight", "princess", "queen", "king", "castle",
    "forest", "cave", "desert", "island", "volcano",
    "waterfall", "canyon", "lake", "pond", "beach",
    "park", "jungle", "valley", "hill", "field",
    "meadow", "farm", "orchard", "vineyard", "market",
    "school", "hospital", "library", "museum", "zoo",
    "restaurant", "cafe", "cinema", "theater", "concert",
    "puzzle", "game", "riddle", "challenge", "quest",
    "adventure", "journey", "treasure", "map", "compass",
    "key", "lock", "chest", "ship", "pirate",
    "island", "ocean", "treasure", "hunt", "ancient",
    "mystery", "legend", "myth", "folklore", "fable",
    "fairytale", "story", "novel", "poem", "verse",
    "song", "music", "instrument", "art", "painting",
    "sculpture", "drawing", "sketch", "portrait", "landscape",
    "abstract", "impressionism", "expressionism", "realism", "surrealism",
    "modernism", "postmodernism", "renaissance", "baroque", "classical",
    "romanticism", "symbolism", "neoclassicism", "cubism", "futurism",
    "dadaism", "surrealism", "pointillism", "minimalism", "pop",
    "contemporary", "installation", "performance", "conceptual", "video",
    "digital", "mixed", "media", "photography", "cinematography",
    "animation", "cartoon", "comic", "manga", "anime",
    "fantasy", "science", "fiction", "horror", "mystery",
    "thriller", "romance", "comedy", "drama", "action",
    "adventure", "animation", "documentary", "biography", "history",
    "politics", "philosophy", "psychology", "sociology", "anthropology",
    "economics", "geography", "linguistics", "literature", "poetry",
    "novel", "short", "story", "essay", "article",
    "journal", "diary", "memoir", "autobiography", "biography",
    "encyclopedia", "dictionary", "thesaurus", "grammar", "language",
    "vocabulary", "syntax", "semantics", "phonetics", "pragmatics",
    "morphology", "phonology", "grammar", "syntax", "punctuation",
    "capitalization", "spelling", "vocabulary", "dictionary", "thesaurus",
    "definition", "synonym", "antonym", "homonym", "homophone",
    "homograph", "idiom", "phrase", "expression", "sentence",
    "paragraph", "essay", "composition", "writing", "reading",
    "literacy", "fiction", "nonfiction", "poetry", "prose",
    "drama", "play", "novel", "story", "short",
    "book", "library", "literature", "genre", "classic",
    "modern", "contemporary", "bestseller", "award-winning", "author",
    "writer", "poet", "playwright", "novelist", "critic",
    "editor", "publisher", "reader", "literary", "criticism",
    "analysis", "interpretation", "review", "commentary", "journalism",
    "reporting", "investigative", "interview", "feature", "opinion",
    "editorial", "column", "article", "headline", "byline",
    "press", "media", "journalist", "reporter", "correspondent"
]

with open('word_list.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    for i in range(0, len(words), 5):
        writer.writerow(words[i:i+5])
